### ISSUE TITLE
 Error: Cannot find module 'chalk'

### ISSUE THREAD

**Issue by kylejoeckel** [vuetifyjs/cordova#21]
This is a fresh package i just created using the vue-cli. I used the exact commands provided in this repo, i am able to run 'npm install' then 'npm run dev' will work but as soon as i run 'cordova platform add ios/android' i suddenly am not able to npm run dev or android/ios commands without getting errors of missing modules. 

```
kyle@kyle-Macmini:~/Develop/drive_log$ npm install
npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!
npm WARN deprecated nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.

> fsevents@1.2.4 install /home/kyle/Develop/drive_log/node_modules/fsevents
> node install

npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN webpack-dev-middleware@1.12.2 requires a peer of webpack@^1.0.0 || ^2.0.0 || ^3.0.0 but none was installed.

added 1571 packages in 69.214s
kyle@kyle-Macmini:~/Develop/drive_log$ cordova platform add ios
Using cordova-fetch for cordova-ios@~4.5.4
Adding ios project...
Creating Cordova project for the iOS platform:
        Path: platforms/ios
        Package: io.test.vuetify
        Name: drive_log
iOS project created with cordova-ios@4.5.4
Discovered plugin "cordova-plugin-whitelist" in config.xml. Adding it to the project
Installing "cordova-plugin-whitelist" for ios
Adding cordova-plugin-whitelist to package.json
Saved plugin info for "cordova-plugin-whitelist" to config.xml
Discovered plugin "cordova-plugin-device" in config.xml. Adding it to the project
Installing "cordova-plugin-device" for ios
Adding cordova-plugin-device to package.json
Saved plugin info for "cordova-plugin-device" to config.xml
--save flag or autosave detected
Saving ios@~4.5.4 into config.xml file ...
kyle@kyle-Macmini:~/Develop/drive_log$ npm run ios

> drive_log@1.0.0 ios /home/kyle/Develop/drive_log
> npm run build && cordova run ios


> drive_log@1.0.0 build /home/kyle/Develop/drive_log
> node build/build.js

module.js:487
    throw err;
    ^

Error: Cannot find module 'chalk'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/kyle/Develop/drive_log/build/check-versions.js:1:75)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! drive_log@1.0.0 build: `node build/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the drive_log@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/kyle/.npm/_logs/2018-05-19T21_01_35_365Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! drive_log@1.0.0 ios: `npm run build && cordova run ios`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the drive_log@1.0.0 ios script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/kyle/.npm/_logs/2018-05-19T21_01_35_383Z-debug.log
```

**Comment by kylejoeckel** [comment]
```
kyle@kyle-Macmini:~/Develop/drive_log$ npm run dev

> drive_log@1.0.0 dev /home/kyle/Develop/drive_log
> node build/dev-server.js

module.js:487
    throw err;
    ^

Error: Cannot find module 'chalk'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/kyle/Develop/drive_log/build/check-versions.js:1:75)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! drive_log@1.0.0 dev: `node build/dev-server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the drive_log@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/kyle/.npm/_logs/2018-05-19T21_03_38_591Z-debug.log
```

**Comment by cairinmichie** [comment]
Have you got the latest versions of npm and cordova? This doesn't seem like an issue with our package but more an issue with your environment.

**Comment by ssendev** [comment]
the problem is that after `cordova platform add ios` a second `npm install` is required which isn't in the readme
