### ISSUE TITLE
Cannot run dev

### ISSUE THREAD

**Issue by dmodules** [vuetifyjs/cordova#35]
I have this error when I try to run this command: npm run dev

> Starting dev server...
ℹ ｢wdm｣: wait until bundle finished: 
(node:8199) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::8080
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at Server.setupListenHandle [as _listen2] (net.js:1367:14)
    at listenInCluster (net.js:1408:12)
    at Server.listen (net.js:1492:7)
    at Function.listen (/media/martincote/ExtraDrive11/sources/vuetify-cordova/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/media/martincote/ExtraDrive11/sources/vuetify-cordova/build/dev-server.js:82:18)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3

npm ERR! Linux 4.15.0-34-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "dev"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! vuetify-cordova@1.0.0 dev: `node build/dev-server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the vuetify-cordova@1.0.0 dev script 'node build/dev-server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the vuetify-cordova package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build/dev-server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs vuetify-cordova
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls vuetify-cordova
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /media/martincote/ExtraDrive11/sources/vuetify-cordova/npm-debug.log

**Comment by KaelWD** [comment]
Something else is already using port 8080
